<div class="container">
  <div class="jumbotron">
    <h2>Golden Gate Bridge with Legos   </h2>
  </div>
  <div class = "lego">
      <p>Breaking news! Reporting from IGN, The Avengers have finally thwarted the evil cyborg space goats attacking San Francisco. As a result, most of the city has been levelled and reconstruction efforts have already started. In the meantime, an unknown government agency has decided to pay for a memorial in place of the Golden Gate Bridge. To assist in the funding, IGN and Lego has decided to contribute and in return the memorial will be a replica of the Golden Gate Bridge made from Legos! </p>
      <p>Code Foo 6 potential candidate, Jarrett Pon, has been asked to help with the project and determine how many Legos the memorial would take. Here is his analysis:</p>
      <p>So let's get right into it. Here is a drawing of the original Golden Gate Bridge: </p>
      <img src="img/legos/img1.png">
      <p></p>
      <p>The destruction of the bridge mainly came from the aimless goats that kept running into it while flying around on jetpacks. Combine that with a few hulk smashes and Ironman being Ironman, the main portion of the bridge is non-existent. After clearing the remaining debris, this is what is left of the bridge: </p>
      <img src="img/legos/img2.png">
      <p></p>
      <p>Yes, I know. It looks so empty, that is why a memorial need to be put in place! Since the memorial will not be in actual use, the Lego replica of the Golden Gate Bridge will be built purely for aesthetics and to look as close to the original as possible. </P>
      <p>In my research, I started with looking up the dimensions of the bridge. However, I wanted it to be as detailed as possible and spent hours looking for exact dimensions from every part of the tower to the size of the cross sections underneath the bridge. After even looking for blueprints, I could only find general dimensions for the bridge. At this stage of the project, I decided to make assumptions on the details I needed which can be confirmed at a later stage. </p>
      <p>Next, I decided to find the amount of Legos needed by splitting up the parts of the bridge and then summing the parts at the end. The sections I split the calculations are by the towers, main road including the cross-section bars underneath, and the wiring. </p>
      <p>As for selecting Lego pieces, I am only going by standard pieces offered and sold by Lego. After searching through <a href="http://www.bricklink.com/">bricklink</a>, a website marketplace only for Lego pieces, the largest brick piece made by Lego is <a href = "http://alpha.bricklink.com/pages/clone/catalogitem.page?P=30072#T=C">12X24 in studs.</a> Since cost has not been a factor for this project, I made the decision to use the 12X24 Lego piece for the tower and main road section. The largest lego brick offers better design and structural integrity. Even with superglue, the best design is obviously not to stack the Lego bricks on top of each other. Although my assignment was only to find the number of Lego bricks needed, here is an image of the staggered stack that could be used: </p>
      <img src ="img/legos/img3.png">
      <p>With this staggered stack, the sides of the Lego replica will not be perfectly smooth. A solution to make the sides more smooth is to add in smaller Lego pieces.  However given the relative size between the memorial and a Lego piece, this would not add visible aesthetic value. Therefore no other pieces besides the 12X24 bricks will be used for the tower and road sections to save on adding unnecessary Lego pieces and cost.</p>
      <p>Next I had to select a Lego piece for the wiring portion of the bridge. Since we do want this to be flexible like the actual wiring on the bridge, string could be used for this section. Again using <a href="http://www.bricklink.com/">bricklink</a>, the longest string piece with connectors is <a href="http://alpha.bricklink.com/pages/clone/catalogitem.page?P=x127c41#T=C">41 stud lengthh</a> long. The entire wiring portion could be made with string however there is no sponsorship with a string company, only Lego and IGN. Therefore the entire wiring will be made with string Lego pieces with end connectors.</p>
      <p>With the type of Lego pieces selected, next I went through each section and found the volume of those sections to determine the Lego pieces needed.</p>
      <hr>
      <p>First section to determine is the road with cross section underneath. Here is a picture of the original bridge:</p>
      <img src = "img/legos/img4.jpg">
      <p></p>
      <p>The difficult part is finding the volume needed for the cross section underneath. Since the design is aesthetic, a design decision has been made to just have Lego pieces build only the sides of the cross section area and leave the space in between empty. </p>
      <p>To make the calculation simpler, one cross section will be considered as such:</p>
      <img src ="img/legos/img5.png">
      <p>From the above image of the golden gate bridge, there are 174 of such sections (half of which are the same cross section image as above but turned 90 degrees) between the towers. The distance between the two towers is 1,280 meters.<sup>[1]</sup> Dividing this distance by 174 gives 7.356 m for the width of each cross section. The full length of the bridge we are replicating is 1966 meters.<sup>[1]</sup> Dividing the distance of the whole bridge by the distance of one cross section gives 267.3 cross sections. Instead of having 0.3 sections on either end, a slight gap will be left to have full sections all the way across. </p>
      <p>To keep things simple for our Lego builders, the width of each cross section will be the same height as the cross section. For each individual bar, the length is already determined by the length or height of the cross section. To determine the thickness of the individual bar, we'll keep it simple and have them be the same distance. Here is a picture of the cross-sections:</p>
      <img src="img/legos/img6.jpg">
      <p></p>
      <p>Since I could not readily find the dimensions of the cross section bars, I will assume it to be one tenth of the total length of one cross section. That makes the thickness of each individual bar to be 0.7356 meters. Using Pythagorean Theorem, the length of the center bar is 10.40 meters. The length of each bar of the four sides will be 7.356 meters - 0.7356 meters (so that the bars don't overlap) which is 6.6204 meters. The total volume of one cross section will be (4(6.6204) + 10.40 )*(0.7356*0.7356) which equals 19.96 meters cubed. With 267 individual cross sections per side, the total volume for cross section part of the bridge is 267*2*19.96 equals 10,660 meters cubed.</p>
      <p>This only gives us the sides of the road, they must be connected on the top before the road can be placed. The road is 19 meters wide. The width of one sidewalk is 3 meters. The actual width of the bridge is 27 meters. This means that the bridge extends one meter out from both sides. To determine the volume of the top of the cross section, we'll use the same thickness of each bar. Therefore the volume of the top slab is 0.7356*27*1966 which equals 39,050 meters cubed.</p>
      <p>The concrete for the road is two inches thick<sup>[1]</sup> which equals 0.0508 meters. The typical height of a curb is 0.2 meters. The volume of the road portion is 0.0508*19*1966 which equals 1898 meters cubed. The volume of the sidewalk is 2*3*(2+0.0508)*1966 which equals 24191 meters cubed.</p>
      <p>The total volume of the road with cross section is 10,660 + 39,050 + 1,898 + 24,191 which equals 75,799 meters cubed.</p>
      <p>To determine the volume of one 12X24 Lego brick, I found that one stud has a length of 0.008 meters and total height of a Lego brick is 0.0096 meters (not including the connector part).<sup>[2]</sup> The volume of one 12X24 Lego brick is then 12*0.008*24*0.008*0.0096 which equals 1.77E-4 meters cubed. </p>
      <p>The number of Lego bricks needed for the road and cross section is 75,799/(1.77E-4) which equals <strong>428,242,938 pieces.</strong></p>
      <hr>
      <p>Next the Lego pieces for the towers need to be determined. Here is a picture of one tower:</p>
      <img src="img/legos/img7.gif">
      <p></p>
      <p>The height each tower is 227 meters.<sup>[1]</sup> The width of each leg is 10 meters and the length of each leg is 16 meters.<sup>[1]</sup> In the image above, the dimensions of each leg decreases after the second arch. For the Lego memorial, the dimensions will stay the same from bottom to top. If a design decision changes later, it is better to overestimate the Legos needed than to underestimate. The volume of four legs will be 4*227*16*10 which equals 145,280 meters cubed. </p>
      <p>Now the two crosses below the road and four connections above the road need to be accounted for. In this image you can see the road sits perfectly between the legs:</p>
      <img src="img/legos/img8.jpg">
      <p></p>
      <p>Therefore the assumption is that the distance between each leg is the same as the total width of the cross section of the bridge at 27 meters. Without official dimensions of the connections and crosses between the legs, I make the assumption that the height of the connections above the road is 16 meters and the height of the crosses below the road is 10 meters. The width of the connections and crosses will be assumed to be half of the leg length at 8 meters.</p>
      <p>Even though the connections on the original bridge get smaller as they go up, the dimensions are the same for the memorial and can change in later design stage. The volume of the four connectors above the road for two towers will be 2*4*27*16*8 which equals 27,648 meters cubed.</p>
      <p>Below the road, the crosses are composed of five bars. Two for each cross and a bar in between the crosses. The length of the bar in between is 27 meters (width of bridge). Making the assumption that the crosses lay inside a square, the length of one cross can be determined with Pythagorean Theorem again will equal 38.2 meters. Since the crosses obviously overlap, the volume created at the junction will have to be subtracted once. Below the road, the crosses have a height of 10 meters and a width of 8 meters. Therefore the volume in at the junction of the cross is 10*10*8 which equals 800 meters cubed. So the total volume of the crosses under the road for both towers is 2*(27*8*10 + 2*(2*(38.2*10*8) - 800) which equals 25,568 meters cubed. For clarification, the calculation above is: 2 towers * (volume of bar in between crosses + 2 crosses * (2 bars *(volume of one bar) - volume of overlap).</p>
      <p>The total volume of the bridge towers is 145,280 + 27,648 + 25,568 = 198,496 meters cubed. </p>
      <p>The number of Lego bricks needed for the towers is 198496/(1.77E-4) which equals <strong>1,121,446,328 pieces.</strong></p>
      <hr>
      <p>Last part to calculate is the wiring.</p>
      <p>The diameter of the Lego string is <a href ="http://www.brickowl.com/catalog/lego-hose-nozzle-with-handle-with-string">0.3 centimeters</a> or 0.003 meters. As stated previously, the length of the longest Lego string with connector is 41 studs long or 0.328 meters. The diameter of one main wire is 0.92 meters and the length of one main cable is 2,332 meters.<sup>[1]</sup> The cross sectional area of the main wire is pi*(0.92*0.92)/4 which equals 0.665 meters squared. Cross sectional area of one Lego string is pi*(0.003*0.003)/4 which equals 7.07E-6 meters squared. That means we can squish together 0.665/7.07E-6 or 94,078 strings in one main cable. If a single Lego string was laid end to end, it would take 2,332/0.328 or 7,110 strings. For both main cables, the total number of Lego strings needed are 94,078*7710 or <strong>748,471,380 pieces.</strong></p>
      <p>The bridge also has 250 pairs of vertical suspender ropes that are spaced out 50 feet apart and are 2-11/16 inches or 0.0683 meters in diameter.<sup>[1]</sup> Since there is no official record of the total length of the suspender ropes, I had to do personal calculations in excel. This calculation is an approximation because it assumes the top of the main cable to the point it touches the bridge is a straight line. With this calculation the length of Lego string needed will be slightly overestimated. As stated before, overestimating is better than underestimating the Legos needed.</p>
      <p>In the diagram below, the orange dots show where each suspender rope would go:</p>
      <img src = "img/legos/img9.png">
      <p>To elaborate, the orange dots represent each suspender rope. The length of the bridge is 1,970 meters, and the towers are placed at 345 meters from the start and end of the bridge.<sup>[1]</sup> Also the height above the roadway is 152 meters.<sup>[1]</sup> There are 125 dots and are spread approximately 50 feet apart. The sum of all the heights are 9,501 meters (only one side). The cross-sectional area of a suspender rope is pi*(0.0683*0.0683)/4 which equals 3.664E-3 meters cubed. That means it takes 3.664E-3/7.07E-6 or 518 Lego strings to construct the necessary area of one suspender rope. For both main cables, the number of Legos needed to make all the suspender ropes is 2*9501*518 which equals to <strong>9,843,036 pieces.</strong></p>
    <p>The below table summarizes the total number of Legos needed:</p>
    <img src="img/legos/img10.png">
    <p></p>
    <p>The total number of Legos needed to rebuild the Golden Gate Bridge is 2,308,003,682 pieces.</p>
    <p>For fun: Using current prices and weights listed for 24X12 bricks and 41L strings, the cost of the Lego pieces alone would be $2,001,392,800 and would weigh 104,788 US tons.</p>
    <p> Citations: </p>
    <p> [1] <a href= "http://goldengatebridge.org/research/factsGGBDesign.php">Golden Gate Bridge: Bridge Design and Construction Statistics</a> </p>
    <p> [2] <a href ="http://www.robertcailliau.eu/Lego/Dimensions/zMeasurements-en.xhtml">Lego Dimensions</a></p>

  </div>
</div>
